/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Clases.ConexionDB;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gerardo
 */
public class Usuarios extends javax.swing.JFrame {

    /**
     * Creates new form Usuarios
     */
    ConexionDB conexion = null;    
    int id_edo;
    public Usuarios() {
        initComponents();
        conexion = new ConexionDB();
        usuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void usuarios(){
        try {
            String consulta = "SELECT NOMBRE, APELLIDO_PAT, APELLIDO_MAT, FECHA_REG, USUARIO, CORREO  FROM EMPLEADO";
            PreparedStatement ps = conexion.conecta.prepareStatement(consulta);
            ResultSet rs = ps.executeQuery();
            ResultSetMetaData rms = rs.getMetaData();
            ArrayList<Object[]> data=new ArrayList<>();
            while(rs.next()){                
                Object [] rows = new Object[rms.getColumnCount()];
                for(int i=0; i<rows.length;i++){
                    rows[i] = rs.getObject(i+1);
                }
                data.add(rows);
            }
            DefaultTableModel dtm = (DefaultTableModel)this.JTBL_Usuarios.getModel();
            for(int i=0;i<data.size();i++){
                dtm.addRow(data.get(i));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: "+ e);
        }
    }
    private void comboEdo(){
        try {
            String consulta = "SELECT ID_ESTADO, ESTADO FROM ESTADO";
            PreparedStatement ps = conexion.conecta.prepareStatement(consulta);
            ResultSet rs = ps.executeQuery();
            jComboEdo.addItem("-Seleccione un estado -");
            while(rs.next()){
                jComboEdo.addItem(rs.getString("ESTADO"));
                id_edo = rs.getInt("ID_ESTADO");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void nuevoUsr(){
        String nombre, aP, aM, usr, pass, correo,fecha;
        
        int id_empleado=0, id_direccion = 0;
        
        nombre = jTextNombre.getText();
        aP = jTextAP.getText();
        aM = jTextAM.getText();
        usr = jTextUsr.getText();
        pass = jPassword.getText();
        correo = jTextCorreo.getText();
        fecha = JLBL_Fecha1.getFecha();
        
        try {
            String consulta = "SELECT MAX (ID_EMPLEADO)+1 FROM EMPLEADO";
            PreparedStatement ps = conexion.conecta.prepareStatement(consulta);
            ResultSet rs = ps.executeQuery();
            if(rs.next()){
                id_empleado = rs.getInt(1);
            }

            consulta = "INSERT INTO EMPLEADO VALUES ('"+id_empleado+"','"+nombre+"','"+aP+"','"+aM+"','"+fecha+"','"+usr+"', '"+pass+"','"+correo+"','"+id_empleado+"')";
            ps = conexion.conecta.prepareStatement(consulta);
            rs = ps.executeQuery();
            //insertDireccion();
            JOptionPane.showMessageDialog(null, "¡Alta de usuario exitosa!");
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en: "+ e);
        }
    }
    private void insertDireccion(){
        int cp, interior, exterior,id_direccion = 0;
        String calle, alcaldia ;
        calle = jTextCalle.getText();
        alcaldia = jTextAlcaldia.getText();
        cp = Integer.parseInt(jTextCP.getText());
        interior = Integer.parseInt(jTextNI.getText());
        exterior = Integer.parseInt(jTextNE.getText());
        try {
            String consulta = "SELECT MAX (ID_DIRECCION)+1 FROM DIRECCION";
            PreparedStatement ps = conexion.conecta.prepareStatement(consulta);
            ResultSet rs = ps.executeQuery();
            if(rs.next()){
                id_direccion = rs.getInt(1);
            }
             consulta = "INSERT INTO DIRECCION VALUES ('"+id_direccion+"','"+calle+"','"+alcaldia+"','"+cp+"','"+interior+"','"+exterior+"','"+id_edo+"') ";
             ps = conexion.conecta.prepareStatement(consulta);
            rs = ps.executeQuery();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error:" + e);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrameNewUsr = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        JPNL_Encabezado1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel_Footer1 = new javax.swing.JPanel();
        jTexTotal1 = new javax.swing.JTextField();
        rSLabelHora2 = new rojeru_san.rsdate.RSLabelHora();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        JLBL_Fecha2 = new rojeru_san.rsdate.RSLabelFecha();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextAP = new javax.swing.JTextField();
        jTextAM = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextUsr = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jTextCorreo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jComboEdo = new javax.swing.JComboBox<>();
        jTextNI = new javax.swing.JTextField();
        jTextAlcaldia = new javax.swing.JTextField();
        jTextCalle = new javax.swing.JTextField();
        jTextNE = new javax.swing.JTextField();
        jTextCP = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        JLBL_Fecha1 = new rojeru_san.rsdate.RSLabelFecha();
        jPanel1 = new javax.swing.JPanel();
        JPNL_Encabezado = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel_Footer = new javax.swing.JPanel();
        jTexTotal = new javax.swing.JTextField();
        rSLabelHora1 = new rojeru_san.rsdate.RSLabelHora();
        JLBL_Fecha = new rojeru_san.rsdate.RSLabelFecha();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTBL_Usuarios = new rojerusan.RSTableMetro();
        jButtonNewUsr = new javax.swing.JButton();
        jButtonBck = new javax.swing.JButton();

        jFrameNewUsr.setPreferredSize(new java.awt.Dimension(920, 660));
        jFrameNewUsr.setSize(new java.awt.Dimension(920, 660));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPNL_Encabezado1.setBackground(new java.awt.Color(236, 236, 236));

        jLabel4.setFont(new java.awt.Font("Raleway", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(24, 23, 37));
        jLabel4.setText("Nuevo usuarios");

        javax.swing.GroupLayout JPNL_Encabezado1Layout = new javax.swing.GroupLayout(JPNL_Encabezado1);
        JPNL_Encabezado1.setLayout(JPNL_Encabezado1Layout);
        JPNL_Encabezado1Layout.setHorizontalGroup(
            JPNL_Encabezado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNL_Encabezado1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel4)
                .addContainerGap(741, Short.MAX_VALUE))
        );
        JPNL_Encabezado1Layout.setVerticalGroup(
            JPNL_Encabezado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel2.add(JPNL_Encabezado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 60));

        jPanel_Footer1.setBackground(new java.awt.Color(255, 255, 255));

        jTexTotal1.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jTexTotal1.setForeground(new java.awt.Color(109, 109, 109));
        jTexTotal1.setBorder(null);
        jTexTotal1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTexTotal1PropertyChange(evt);
            }
        });

        rSLabelHora2.setForeground(new java.awt.Color(109, 109, 109));
        rSLabelHora2.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Ventas/Icono_Reloj.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Ventas/Icono_Calendario.png"))); // NOI18N

        JLBL_Fecha2.setForeground(new java.awt.Color(109, 109, 109));
        JLBL_Fecha2.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        JLBL_Fecha2.setFormato("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel_Footer1Layout = new javax.swing.GroupLayout(jPanel_Footer1);
        jPanel_Footer1.setLayout(jPanel_Footer1Layout);
        jPanel_Footer1Layout.setHorizontalGroup(
            jPanel_Footer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Footer1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSLabelHora2, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(394, 394, 394)
                .addComponent(jTexTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(359, 359, 359))
            .addGroup(jPanel_Footer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_Footer1Layout.createSequentialGroup()
                    .addGap(278, 278, 278)
                    .addComponent(JLBL_Fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(617, Short.MAX_VALUE)))
        );
        jPanel_Footer1Layout.setVerticalGroup(
            jPanel_Footer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Footer1Layout.createSequentialGroup()
                .addGroup(jPanel_Footer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_Footer1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_Footer1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel_Footer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rSLabelHora2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTexTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Footer1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(9, 9, 9))
            .addGroup(jPanel_Footer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_Footer1Layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(JLBL_Fecha2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel2.add(jPanel_Footer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 920, 60));

        jLabel1.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel1.setText("NOMBRE");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel2.setText("APELLIDO PATERNO");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel5.setText("APELLIDO MATERNO");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jTextNombre.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jPanel2.add(jTextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 190, -1));

        jTextAP.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jPanel2.add(jTextAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 190, -1));

        jTextAM.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jPanel2.add(jTextAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 190, -1));

        jLabel6.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel6.setText("USUARIO");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, -1, -1));

        jLabel11.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel11.setText("CONTRASEÑA");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, -1, -1));

        jTextUsr.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jPanel2.add(jTextUsr, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 200, -1));

        jPassword.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jPanel2.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 200, -1));

        jLabel12.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel12.setText("CORREO");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, -1));

        jTextCorreo.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jPanel2.add(jTextCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 200, -1));

        jLabel13.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel13.setText("CALLE");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jLabel14.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel14.setText("ALCALDIA");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        jLabel15.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel15.setText("C.P");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, -1, -1));

        jLabel16.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel16.setText("NO. INTERIOR");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, -1, -1));

        jLabel17.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel17.setText("NO. EXTERIOR");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        jComboEdo.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jPanel2.add(jComboEdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, 200, -1));

        jTextNI.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jPanel2.add(jTextNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, 200, -1));

        jTextAlcaldia.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jPanel2.add(jTextAlcaldia, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 190, -1));

        jTextCalle.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jPanel2.add(jTextCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 190, -1));

        jTextNE.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jPanel2.add(jTextNE, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 190, -1));

        jTextCP.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jPanel2.add(jTextCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 320, 200, -1));

        jButton1.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jButton1.setText("INGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, -1, -1));

        jButton2.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 520, -1, -1));

        jLabel18.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel18.setText("FECHA");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, -1));

        JLBL_Fecha1.setForeground(new java.awt.Color(109, 109, 109));
        JLBL_Fecha1.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        JLBL_Fecha1.setFormato("dd-MM-yy");
        jPanel2.add(JLBL_Fecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 154, 47));

        javax.swing.GroupLayout jFrameNewUsrLayout = new javax.swing.GroupLayout(jFrameNewUsr.getContentPane());
        jFrameNewUsr.getContentPane().setLayout(jFrameNewUsrLayout);
        jFrameNewUsrLayout.setHorizontalGroup(
            jFrameNewUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrameNewUsrLayout.setVerticalGroup(
            jFrameNewUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPNL_Encabezado.setBackground(new java.awt.Color(236, 236, 236));

        jLabel3.setFont(new java.awt.Font("Raleway", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(24, 23, 37));
        jLabel3.setText("Usuarios");

        javax.swing.GroupLayout JPNL_EncabezadoLayout = new javax.swing.GroupLayout(JPNL_Encabezado);
        JPNL_Encabezado.setLayout(JPNL_EncabezadoLayout);
        JPNL_EncabezadoLayout.setHorizontalGroup(
            JPNL_EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNL_EncabezadoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addContainerGap(799, Short.MAX_VALUE))
        );
        JPNL_EncabezadoLayout.setVerticalGroup(
            JPNL_EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(JPNL_Encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 60));

        jPanel_Footer.setBackground(new java.awt.Color(255, 255, 255));

        jTexTotal.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jTexTotal.setForeground(new java.awt.Color(109, 109, 109));
        jTexTotal.setBorder(null);
        jTexTotal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTexTotalPropertyChange(evt);
            }
        });

        rSLabelHora1.setForeground(new java.awt.Color(109, 109, 109));
        rSLabelHora1.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N

        JLBL_Fecha.setForeground(new java.awt.Color(109, 109, 109));
        JLBL_Fecha.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        JLBL_Fecha.setFormato("yyyy-MM-dd");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Ventas/Icono_Reloj.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_Ventas/Icono_Calendario.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_FooterLayout = new javax.swing.GroupLayout(jPanel_Footer);
        jPanel_Footer.setLayout(jPanel_FooterLayout);
        jPanel_FooterLayout.setHorizontalGroup(
            jPanel_FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_FooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSLabelHora1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(JLBL_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237)
                .addComponent(jTexTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(359, 359, 359))
        );
        jPanel_FooterLayout.setVerticalGroup(
            jPanel_FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_FooterLayout.createSequentialGroup()
                .addGroup(jPanel_FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_FooterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_FooterLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel_FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rSLabelHora1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTexTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_FooterLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(JLBL_Fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(9, 9, 9))
        );

        jPanel1.add(jPanel_Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 920, 60));

        JTBL_Usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE", "APELLIDO PATERNO", "APELLIDO MATERNO", "FECHA DE REGISTRO", "USUARIO", "CORREO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTBL_Usuarios.setAltoHead(30);
        JTBL_Usuarios.setColorBackgoundHead(new java.awt.Color(34, 41, 50));
        JTBL_Usuarios.setColorBordeFilas(new java.awt.Color(109, 109, 109));
        JTBL_Usuarios.setColorBordeHead(new java.awt.Color(255, 255, 255));
        JTBL_Usuarios.setColorFilasBackgound2(new java.awt.Color(230, 230, 230));
        JTBL_Usuarios.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        JTBL_Usuarios.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        JTBL_Usuarios.setColorSelBackgound(new java.awt.Color(54, 63, 73));
        JTBL_Usuarios.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        JTBL_Usuarios.setFuenteFilas(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        JTBL_Usuarios.setFuenteFilasSelect(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        JTBL_Usuarios.setFuenteHead(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        JTBL_Usuarios.setGridColor(new java.awt.Color(255, 255, 255));
        JTBL_Usuarios.setGrosorBordeFilas(0);
        JTBL_Usuarios.setGrosorBordeHead(0);
        JTBL_Usuarios.setRowHeight(30);
        JTBL_Usuarios.setSelectionBackground(new java.awt.Color(66, 63, 102));
        JTBL_Usuarios.getTableHeader().setReorderingAllowed(false);
        JTBL_Usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTBL_UsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTBL_Usuarios);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 920, 280));

        jButtonNewUsr.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jButtonNewUsr.setText("CREAR USUARIO");
        jButtonNewUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewUsrActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNewUsr, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, -1, -1));

        jButtonBck.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jButtonBck.setText("REGRESAR");
        jButtonBck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBckActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBck, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTexTotalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTexTotalPropertyChange
        jTexTotal.setHorizontalAlignment((int) CENTER_ALIGNMENT);
    }//GEN-LAST:event_jTexTotalPropertyChange

    private void JTBL_UsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTBL_UsuariosMouseClicked

    }//GEN-LAST:event_JTBL_UsuariosMouseClicked

    private void jButtonNewUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewUsrActionPerformed
        comboEdo();
        jFrameNewUsr.setVisible(true);
    }//GEN-LAST:event_jButtonNewUsrActionPerformed

    private void jButtonBckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBckActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonBckActionPerformed

    private void jTexTotal1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTexTotal1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexTotal1PropertyChange

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jFrameNewUsr.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        nuevoUsr();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static rojeru_san.rsdate.RSLabelFecha JLBL_Fecha;
    public static rojeru_san.rsdate.RSLabelFecha JLBL_Fecha1;
    public static rojeru_san.rsdate.RSLabelFecha JLBL_Fecha2;
    private javax.swing.JPanel JPNL_Encabezado;
    private javax.swing.JPanel JPNL_Encabezado1;
    private rojerusan.RSTableMetro JTBL_Usuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonBck;
    private javax.swing.JButton jButtonNewUsr;
    private javax.swing.JComboBox<String> jComboEdo;
    private javax.swing.JFrame jFrameNewUsr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_Footer;
    private javax.swing.JPanel jPanel_Footer1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTexTotal;
    private javax.swing.JTextField jTexTotal1;
    private javax.swing.JTextField jTextAM;
    private javax.swing.JTextField jTextAP;
    private javax.swing.JTextField jTextAlcaldia;
    private javax.swing.JTextField jTextCP;
    private javax.swing.JTextField jTextCalle;
    private javax.swing.JTextField jTextCorreo;
    private javax.swing.JTextField jTextNE;
    private javax.swing.JTextField jTextNI;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextUsr;
    private rojeru_san.rsdate.RSLabelHora rSLabelHora1;
    private rojeru_san.rsdate.RSLabelHora rSLabelHora2;
    // End of variables declaration//GEN-END:variables
}
